# Generated by Django 4.2.6 on 2023-11-04 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CalorieCalc', '0002_customuser_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='height',
            field=models.DecimalField(decimal_places=2, default=213.36, max_digits=5),
            preserve_default=False,
        ),
    ]
