# Generated by Django 4.2.6 on 2023-11-19 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CalorieCalc', '0004_foodlog_exerciselog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=200)),
                ('quantity', models.DecimalField(decimal_places=2, default=100.0, max_digits=7)),
                ('calories', models.IntegerField(default=0)),
                ('fat', models.DecimalField(decimal_places=2, max_digits=7)),
                ('carbohydrates', models.DecimalField(decimal_places=2, max_digits=7)),
                ('protein', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.RenameField(
            model_name='foodlog',
            old_name='description',
            new_name='unit',
        ),
        migrations.RemoveField(
            model_name='foodlog',
            name='item',
        ),
        migrations.AddField(
            model_name='foodlog',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=12, max_digits=7),
            preserve_default=False,
        ),
    ]
