# Generated by Django 4.2.6 on 2023-11-19 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CalorieCalc', '0005_food_rename_description_foodlog_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodlog',
            name='food_consumed',
            field=models.ForeignKey(default=14, on_delete=django.db.models.deletion.CASCADE, to='CalorieCalc.food'),
            preserve_default=False,
        ),
    ]
