# Generated by Django 4.2.6 on 2023-11-19 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CalorieCalc', '0006_foodlog_food_consumed'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='category_name',
            field=models.CharField(default=14, max_length=50),
            preserve_default=False,
        ),
    ]
