# Generated by Django 4.2.6 on 2023-11-22 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CalorieCalc', '0007_food_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='category_name',
        ),
        migrations.AddField(
            model_name='foodlog',
            name='weight',
            field=models.TextField(blank=True, null=True),
        ),
    ]
