# Generated by Django 4.2.6 on 2023-11-22 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CalorieCalc', '0008_remove_food_category_name_foodlog_weight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodlog',
            old_name='calorie',
            new_name='calories',
        ),
        migrations.AlterField(
            model_name='foodlog',
            name='food_consumed',
            field=models.TextField(default='', max_length=100),
        ),
    ]
