# Generated by Django 4.2.6 on 2023-11-22 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CalorieCalc', '0009_rename_calorie_foodlog_calories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodlog',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=7),
        ),
        migrations.AlterField(
            model_name='foodlog',
            name='unit',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='foodlog',
            name='weight',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
