# Generated by Django 4.2.6 on 2023-11-22 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CalorieCalc', '0011_alter_foodlog_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodlog',
            name='date_logged',
        ),
    ]
