# Generated by Django 4.2.6 on 2023-11-23 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CalorieCalc', '0012_remove_foodlog_date_logged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodlog',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
