# Generated by Django 4.2.6 on 2023-11-26 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CalorieCalc', '0013_alter_foodlog_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exerciselog',
            name='date_logged',
        ),
        migrations.AlterField(
            model_name='exerciselog',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
