# Generated by Django 4.2.6 on 2023-11-28 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CalorieCalc', '0015_weight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='quantity',
            new_name='serving_size',
        ),
        migrations.AddField(
            model_name='food',
            name='cholestrol',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='fiber',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='sugar',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=7),
            preserve_default=False,
        ),
    ]
