# Generated by Django 4.2.6 on 2023-12-03 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CalorieCalc', '0017_plan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='current',
            new_name='current_weight',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='duration',
            new_name='target_duration',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='target',
            new_name='target_weight',
        ),
    ]
