# Generated by Django 4.2.6 on 2023-12-03 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CalorieCalc', '0018_rename_current_plan_current_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='target_rate',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
