# Generated by Django 4.2.6 on 2023-12-04 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CalorieCalc', '0019_plan_target_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodlog',
            old_name='weight',
            new_name='serving_weight',
        ),
    ]
