# Generated by Django 4.2.6 on 2023-12-04 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CalorieCalc', '0020_rename_weight_foodlog_serving_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciselog',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
